<?php
/**
 * MagedIn Technology
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  MagedIn
 * @copyright Copyright (c) 2024 MagedIn Technology.
 *
 * @author    MagedIn Support <support@magedin.com>
 */

declare(strict_types=1);

namespace MagedIn\EnhancedCatalog\Model;

use Magento\Framework\App\Config\ScopeConfigInterface;
use Magento\Framework\App\Helper\AbstractHelper;

/**
 * DocBlock for Config class.
 */
class Config extends AbstractHelper
{
    /**
     * @var string
     */
    private const XPATH_DEFAULT_SORT_ORDER = 'catalog/frontend/default_sort_order';

    /**
     * DocBlock for method.
     *
     * @param string $scopeType
     * @param int|string|null $scopeCode
     *
     * @return string
     */
    public function getProductListingDefaultSortOrder(
        string $scopeType = ScopeConfigInterface::SCOPE_TYPE_DEFAULT,
        $scopeCode = null
    ): string {
        return $this->scopeConfig->getValue(self::XPATH_DEFAULT_SORT_ORDER, $scopeType, $scopeCode);
    }
}
