<?php
/**
 * MagedIn Technology
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  MagedIn
 * @copyright Copyright (c) 2025 MagedIn Technology.
 *
 * @author    MagedIn Support <support@magedin.com>
 */

declare(strict_types=1);

namespace MagedIn\EnhancedCatalog\Plugin\Block\Product\ProductList;

use Magento\Catalog\Block\Product\ProductList\Toolbar;
use MagedIn\EnhancedCatalog\Model\Config;
use MagedIn\EnhancedCatalog\Model\Config\Source\SortOrder;

/**
 * DocBlock for ToolbarPlugin class.
 */
class ToolbarPlugin
{
    private Config $config;

    /**
     * @param Config $config
     */
    public function __construct(
        Config $config
    ) {
        $this->config = $config;
    }

    /**
     * DocBlock for method.
     *
     * @param Toolbar $subject
     *
     * @return void
     */
    public function beforeGetCurrentDirection(Toolbar $subject): void
    {
        $defaultDirection = $this->config->getProductListingDefaultSortOrder();
        if (!empty($defaultDirection) && in_array(strtolower($defaultDirection), SortOrder::SORT_OPTIONS)) {
            $subject->setDefaultDirection($defaultDirection);
        }
    }
}
