<?php
/**
 * MagedIn Technology
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  MagedIn
 * @copyright Copyright (c) 2024 MagedIn Technology.
 *
 * @author    MagedIn Support <support@magedin.com>
 */

namespace MagedIn\EnhancedCatalog\Model\Config\Source;

use Magento\Framework\Data\OptionSourceInterface;

class SortOrder implements OptionSourceInterface
{
    public const SORT_ASC = 'asc';
    public const SORT_DESC = 'desc';
    public const SORT_OPTIONS = [self::SORT_ASC, self::SORT_DESC];

    /**
     * Retrieve option values array
     *
     * @return array
     */
    public function toOptionArray(): array
    {
        return [
            [
                'value' => self::SORT_ASC,
                'label' => __('Oldest to Newest'),
            ], [
                'value' => self::SORT_DESC,
                'label' => __('Newest to Oldest'),
            ],
        ];
    }
}
